LEFT_CLICK = '<ButtonRelease-1>'
CTRL_LEFT_CLICK = '<Control-ButtonRelease-1>'

STYLE_CONFIG_KEYS = frozenset({
    'activebackground',
    'activeforeground',
    'activerelief',
    'background',
    'bd',
    'bg',
    'border',
    'borderwidth',
    'buttonbackground',
    'buttoncursor',
    'buttondownrelief',
    'buttonuprelief',
    'cursor',
    'disabledbackground',
    'disabledforeground',
    'elementborderwidth',
    'fg',
    'font',
    'foreground',
    'highlightbackground',
    'highlightcolor',
    'highlightthickness',
    'insertbackground',
    'insertborderwidth',
    'insertwidth',
    'overrelief',
    'readonlybackground',
    'relief',
    'sashcursor',
    'sashrelief',
    'sashwidth',
    'selectbackground',
    'selectborderwidth',
    'selectcolor',
    'selectforeground',
    'sliderrelief',
    'troughcolor',
    'underline',
    'wraplength',
})
