__title__ = 'music_manager'
__description__ = 'Music Manager'
__url__ = 'https://github.com/dskrypa/music_manager'
__version__ = '2024.12.07-6'
__author__ = 'Doug Skrypa'
__author_email__ = 'dskrypa@gmail.com'
__copyright__ = 'Copyright 2023 Doug Skrypa'
